### ISSUE TITLE
[FAILED] No configuration setting found for key 'pekko.loggers'

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko-persistence-r2dbc#11]
https://github.com/apache/incubator-pekko-persistence-r2dbc/actions/runs/4675006706/jobs/8279690605#step:8:1763
```
Caused by: com.typesafe.config.ConfigException$Missing: system properties: No configuration setting found for key 'pekko.loggers'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:175)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:181)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:263)
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:383)
	at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:441)
	at org.apache.pekko.actor.ActorSystem$Settings$.amendSlf4jConfig(ActorSystem.scala:346)
	at org.apache.pekko.actor.ActorSystemImpl.<init>(ActorSystem.scala:834)
	at org.apache.pekko.actor.typed.ActorSystem$.createInternal(ActorSystem.scala:299)
	at org.apache.pekko.actor.typed.ActorSystem$.apply(ActorSystem.scala:214)
	at org.apache.pekko.actor.testkit.typed.scaladsl.ActorTestKit$.apply(ActorTestKit.scala:101)
	at org.apache.pekko.actor.testkit.typed.scaladsl.ActorTestKitBase.<init>(ActorTestKitBase.scala:46)
	... 30 more
```

**Comment by mdedetrich** [comment]
So the missing key is a red herring, the real cause  appears to be a result of a flaky test with initialisation of the databases
